#!/bin/sh
PHP_VERSION=$(head -1 .phprc)

$PHP_VERSION /usr/local/bin/composer install
unset NPM_CONFIG_PREFIX && . ~/.nvm/nvm.sh && nvm use
npm ci
npm run build
git checkout -- package-lock.json
$PHP_VERSION artisan migrate

if [ -f ./.git/hooks/post-merge ]; then
	./.git/hooks/post-merge $@
fi

exit 0
