name: Shkolo

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build-and-test:
    runs-on: ubuntu-24.04
    container:
      image: appsforskywalker/php-8.3-mongo-base:latest-amd64

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Copy .env
        run: cp .env.example .env

      - name: Install Dependencies
        run: composer install --optimize-autoloader --no-interaction --prefer-dist --no-dev

      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.12.0

      - name: Build Front End
        run: |
          npm ci
          npm run build

      - name: Generate Key
        run: php artisan key:generate
